name: Lupper Auto Generator 24/7

on:
  schedule:
    - cron: '*/5 * * * *' # Inajiwasha yenyewe kila baada ya dakika 5, saa 24/7
  workflow_dispatch:      # Inaruhusu wewe kuwasha kwa mkono (Manual Trigger)

jobs:
  ping_and_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Open Lupper Bot and Generate Code
        run: |
          echo "🚀 Master Lupin, Injini ya LUPPER-MD inawaka sasa hivi..."
          
          # Hapa tunatuma POST request yenye namba ili Render waone kuna activity
          curl -X POST "https://lupin-md-ad9u.onrender.com/pair" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "number=255700000000" \
          --compressed \
          --verbose

          echo "✅ Signal imetumwa! Render wataona bot inafanya kazi."
